### ISSUE TITLE
Exception in SqliteEngine's remove_item due to missing SQLITE_ENABLE_UPDATE_DELETE_LIMIT

### ISSUE THREAD

**Issue by evevseev** [ErikKalkoken/aiodiskqueue#5]
In most cases, Python 3 comes with SQLite which does not have opt-in option `SQLITE_ENABLE_UPDATE_DELETE_LIMIT` enabled. This configuration causes the `SqliteEngine`'s `remove_item` method to raise `Exception near "ORDER": syntax error`, making this engine unusable without recompiling.

https://github.com/ErikKalkoken/aiodiskqueue/blob/79c972dad376654dde19c48f93eddc4ccbb6ec5d/src/aiodiskqueue/engines/sqlite.py#L64C1-L72C18

Tested on macOS using Python 3.11 from Homebrew.

**Comment by evevseev** [comment]
https://github.com/ErikKalkoken/aiodiskqueue/blob/79c972dad376654dde19c48f93eddc4ccbb6ec5d/src/aiodiskqueue/engines/sqlite.py#L64C1-L72C18

**Comment by ErikKalkoken** [comment]
Hey! Thanks for reporting this issue. I have refactored the SQL and it should now also work without that opt-in option. 

Will release this fix shortly. Please let me know if it works for you.

**Comment by ErikKalkoken** [comment]
I am assuming this is fixed and will close the issue. But I am happy to reopen if needed.
